apiVersion: v1
kind: Service
metadata:
  name: sla-calculator
  namespace: st-ab2-islamov
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9101"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: sla-calculator
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
