apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
  namespace: st-ab2-islamov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prober
  template:
    metadata:
      labels:
        app: prober
      annotations:
        sage/group: "ab2_islamov"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: prober
          image: therad445/ab2-prober:v10
          imagePullPolicy: Always
          env:
            - name: TARGET_URL
              value: "http://oncall:8080/"
            - name: SCRAPE_INTERVAL
              value: "30"
            - name: LOG_LEVEL
              value: "INFO"
            - name: METRICS_PORT
              value: "9100"
          ports:
            - containerPort: 9100
              name: metrics
