apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  labels:
    app: my-app
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      color: blue
  template:
    metadata:
      annotations:
        sage/group: "ab2_islamov"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
        prometheus.io/path: "/metrics"
      labels:
        app: my-app
        color: blue
        version: v1.0.0
    spec:
      containers:
        - name: my-app
          image: containersol/k8s-deployment-strategies
          env:
            - name: VERSION
              value: "v1.0.0"
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9101
        - name: json-log-sidecar
          image: busybox:1.36
          command: [ "/bin/sh","-lc" ]
          args:
            - |
              while true; do
                HOST=$(hostname)
                printf '{"env":"st","system":"my-app","inst":"%s","level":"INFO","message":"sidecar heartbeat"}\n' "$HOST"
                sleep 5
              done
          resources:
            requests: { cpu: "5m", memory: "16Mi" }
            limits: { cpu: "50m", memory: "32Mi" }
